# Generated by Django 5.0.6 on 2024-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0004_student_is_active_student_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='course',
            name='is_theory',
            field=models.BooleanField(default=True),
        ),
    ]
